### ISSUE TITLE
'StorageFiles deduplication' Error at the end of the tasks at the top of a list when starting a job (play button pressed)

### ISSUE THREAD

**Issue by Plesuvius** [drweb86/butil#260]
### Error reads: StorageFiles deduplication

LOG:
2023-12-31 10-41-57 New task (Unknown).txt
31 December 2023 10:41 ✅❌

I have **4844** files say to back up across the default directories. Some of these are duplicated file names in different folders.

I have installed and run Duplicate File Detector 7.2.69 and removed any real dupes on the FS as well as using windows_czkawka_gui to check the same directories with a hash algo. The problem at a guess is likely to be **the duplicate long names**. Crash report at the end of the 4844 files, displays file **4840**.

### BUtil BUG Report:

```
BUtil 2023.12.14.0 - Bug report (12/31/2023 10:43)
Please report about it here: 
https://github.com/drweb86/butil
StorageFiles deduplication
   at BUtil.Core.TasksTree.WriteSourceFileToStorageTask..ctor(StorageSpecificServicesIoc services, TaskEvents events, List`1 storageFiles, Quota singleBackupQuotaGb, SourceItemV2 sourceItem, List`1 versionStates) in D:\sources\butil\sources\BUtil.Core\TasksTree\Storage\WriteSourceFileToStorageTask.cs:line 41
   at BUtil.Core.TasksTree.Storage.WriteSourceFilesToStorageTask.<>c__DisplayClass3_1.<Execute>b__7(IGrouping`2 x) in D:\sources\butil\sources\BUtil.Core\TasksTree\Storage\WriteSourceFilesToStorageTask.cs:line 63
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at BUtil.Core.TasksTree.Storage.WriteSourceFilesToStorageTask.Execute() in D:\sources\butil\sources\BUtil.Core\TasksTree\Storage\WriteSourceFilesToStorageTask.cs:line 52
   at BUtil.Core.TasksTree.Core.SequentialBuTask.Execute() in D:\sources\butil\sources\BUtil.Core\TasksTree\Core\SequentialTask.cs:line 23
   at BUtil.Core.TasksTree.WriteIncrementedVersionTask.Execute() in D:\sources\butil\sources\BUtil.Core\TasksTree\IncrementalModel\WriteIncrementedVersionTask.cs:line 51
   at BUtil.Core.TasksTree.Core.SequentialBuTask.Execute() in D:\sources\butil\sources\BUtil.Core\TasksTree\Core\SequentialTask.cs:line 23
   at BUtil.Core.TasksTree.IncrementalModel.IncrementalBackupTask.Execute() in D:\sources\butil\sources\BUtil.Core\TasksTree\IncrementalModel\IncrementalBackupTask.cs:line 40
   at butil_ui.ViewModels.LaunchTaskViewModel.<StartTaskCommand>b__54_0()
BUtil.Core
```

Please check and fix and let me know? Many thanks great software ideas and interface and so on I'd say.

**Comment by drweb86** [comment]
Hi

Regarding deduplication of files. BUtil has deduplication feature. It means that if you have 2 files with identical content in different places, it should detect it and create one backuped file associated with 2 files.

Regarding the exception I see 
```
            if (!StorageFiles.All(x => x.FileState.CompareTo(StorageFiles[0].FileState, true)))
                throw new InvalidOperationException("StorageFiles deduplication");
```
I'll take a look at it tomorrow.

**Comment by Plesuvius** [comment]
Thanks for your valuable work and time so far, and for contacting me
directly as I requested. I'll keep giving you feedback on github if
anything further comes up and I'm glad I found this for us!

Have a happy new year :)
Mr Naveen K Rao
London W6
***@***.***

**Comment by drweb86** [comment]
@Plesuvius , update to latest release, restart backup. 
Once it will fail, add some details here.
I checked code, it looks ok, so I added more debug information inside exception, like file names, sizes, SHA512 etc.

**Comment by Plesuvius** [comment]
That really fast response has fixed it for me and hopefully us all, I now have a successful (there's a typo extra l in that window though!) save of over 9400 files from the default directories. You fixed it, thanks! 
I now feel I'm better at enabling developer debug hehe 

LOGS (fin):
✅ 15:09 Writing state
✅ 15:09 Compressing "C:\Users\nrao8\AppData\Local\Temp\tmp8DF4.tmp.Folder\Incremental Non-Encrypted Non-Compressed Backup State.json" to "C:\Users\nrao8\AppData\Local\Temp\tmp8DF4.tmp.Folder\Incremental Encrypted Compressed Backup State.7z" with password  successfull
✅ 15:09 Copying "C:\Users\nrao8\AppData\Local\Temp\tmp8DF4.tmp.Folder\Incremental Encrypted Compressed Backup State.7z" to "S:\BUtil Backup NVME Boot Docs\Incremental Encrypted Compressed Backup State.7z"
✅ 15:09 Copying "C:\Users\nrao8\AppData\Local\Temp\tmp921B.tmp.Folder\Integrity verification script.ps1" to "S:\BUtil Backup NVME Boot Docs\Integrity verification script.ps1"
✅ 15:09 Unmount
Succesfull

**Comment by Plesuvius** [comment]
Closing. Developers, feel free to reopen if this comes up again. GOOD FIX 01 01 2024
Happy New Year!
